---

- name: Install AIDE
  ansible.builtin.package:
    name: aide
    state: present
  become: true

- name: Configure AIDE
  ansible.builtin.copy:
    src: aide.conf
    dest: /etc/aide.conf
    owner: root
    group: root
    mode: "0600"
  become: true

- name: Check if AIDE is initialized
  ansible.builtin.stat:
    path: /var/lib/aide/aide.db.gz
  register: file_stat

- name: Initialize AIDE
  when: not file_stat.stat.exists
  block:
    - name: Create new AIDE DB
      ansible.builtin.command: "aide --init"
      become: true
      changed_when: true

    - name: Rename AIDE DB
      ansible.builtin.command: "mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz"
      become: true
      changed_when: true
