core:
  users:
    - name: "preinboth"
      password: "$2b$12$BUxfklDq15HetUjHlSeWZOj3hfjjwcMuhVxEKb4HloFM0ZXrgCJH."
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICD9HZowVpcbOdJSneZM9CR57uVai7+clgkSExweXkbF preinboth@wotan.asgaard.dev"
      shell: "/bin/bash"
      groups:
        - users
        - wheel
      create_home: true

  packages:
    all:
    rhel:
      - firewalld
