---

- name: Include RHEL Tasks
  ansible.builtin.include_tasks: rhel.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: Install podman
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items: "{{ podman_packages }}"

- name: Ensure docker.io is the only unqualified registry
  become: true
  ansible.builtin.lineinfile:
    path: /etc/containers/registries.conf
    regexp: '^unqualified-search-registries\s*='
    line: 'unqualified-search-registries = ["docker.io"]'
