---

- name: Install podman
  ansible.builtin.package:
    name: podman
    state: present
  become: true

- name: Symlink docker to podman
  ansible.builtin.file:
    src: /usr/bin/podman
    dest: /usr/local/bin/docker
    state: link
    force: true
    owner: root
    group: root
    mode: "0755"
  become: true
