---

- name: Ensure the crb repository is enabled
  community.general.dnf_config_manager:
    name: crb
    state: enabled
  become: true

- name: Enable EPEL repository
  ansible.builtin.dnf:
    name: epel-release
    state: present
  become: true
