---

- name: Create vaultwarden directories
  ansible.builtin.file:
    path: "/opt/vaultwarten/{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0750"
  become: true
  with_items:
    - vw-data
    - logs
    - pgdata

- name: Create .env file
  ansible.builtin.template:
    src: docker-env.j2
    dest: "/opt/vaultwarden/.env"
    owner: "root"
    group: "root"
    mode: "0640"
  become: true
  notify: Restart Vaultwarden

- name: Create docker-compose file
  ansible.builtin.template:
    src: docker-compose.j2
    dest: "/opt/vaultwarden/compose.yml"
    owner: "root"
    group: "root"
    mode: "0640"
  become: true
  notify: Restart Vaultwarden

- name: Create systemd service
  ansible.builtin.template:
    src: systemd-service.j2
    dest: /etc/systemd/system/vaultwarden.service
    owner: root
    group: root
    mode: "0644"
  become: true
  notify: Reload Systemd

- name: Enable and start Vaultwarden Service
  ansible.builtin.service:
    name: vaultwarden
    state: started
    enabled: true
  become: true
