---

- name: Reload Systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Restart Vaultwarden
  ansible.builtin.service:
    name: vaultwarden
    state: restarted
  become: true
