---

- name: Include RHEL Tasks
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.include_tasks: rhel.yml

- name: Install Docker Packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - "{{ docker_packages }}"

- name: Enable and start Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  become: true
