---

- name: Reload Systemd
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: Restart Seafile
  ansible.builtin.service:
    name: seafile
    state: restarted
  become: true

- name: Reload Firewalld
  ansible.builtin.service:
    name: firewalld
    state: restarted
  become: true
