---

seafile_fqdn: files.asgaard.dev

seafile_admin_email: hello@patrickreinboth.de

seafile_sever_image: seafileltd/seafile-mc:13.0-latest
seafile_db_image: mariadb:10.11
seafile_redis_image: redis
seafile_caddy_image: lucaslorentz/caddy-docker-proxy:2.9-alpine
seafile_seadoc_image: seafileltd/sdoc-server:2.0-latest
seafile_notification_server_image: seafileltd/notification-server:13.0-latest
seafile_md_image: seafileltd/seafile-md-server:13.0-latest
